### ISSUE TITLE
Registation

### ISSUE THREAD

**Issue by larsvandriel** [Tournamanager/webApp#41]
What has to be done:
Create a component that will be used to register users

Why it has to be done:
So that users can create an account with which they can make use of our services.

When the task is done:
The user can fill in an registration form and all the user data will be send to Firebase and the backend.
The data will be checked and when the check fails the frontend will receive an error which it will display to the user.
When the check passes the user will be created and the user can be logged in to the system.

**Comment by MindHawk** [comment]
This user story needs review.

**Comment by MichielLangen** [comment]
this is already done
