### ISSUE TITLE
Resetting password results in dead-end

### ISSUE THREAD

**Issue by lfb0801** [Tournamanager/webApp#59]
**Describe the bug**
If a user forgets their password, the application is able to reset the password. If the user chooses this option, the user gets stuck on the password reset page.

**To Reproduce**
1. Go to the app,
2. Click on "trouble siging in",
3. Get the email with your recovery link,
4. Add your new password
5. See error

**Expected behavior**
The page should redirect me to the login page.

**Screenshots**
![image](https://user-images.githubusercontent.com/16375630/68112399-8432b580-fef1-11e9-939a-0fa2e14079f2.png)

**Comment by MichielLangen** [comment]
Without making our own login page, this is not something we can fix

**Comment by chf3kl9** [comment]
https://stackoverflow.com/questions/55296314/firebase-redirect-to-webpage-after-successful-password-change
