### ISSUE TITLE
Profile pages crashes on reload

### ISSUE THREAD

**Issue by MichielLangen** [Tournamanager/webApp#79]
**Describe the bug**
Refreshing profile page, crashe app

**To Reproduce**
1. Go to 'My Profile page'
2. Click on 'F5'
3. See error

**Expected behavior**
Refresh page

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/28343855/69948395-7ae43b00-14e7-11ea-8b3f-4f82588607eb.png)

**Comment by MichielLangen** [comment]
fixed

**Comment by MichielLangen** [comment]
it was not fixed

**Comment by MindHawk** [comment]
fixed
